/* 
eightball-switch.js--   JavaScript program to give a personalised
                        prognostication based off a random
                        number (between 0-7) generated by the 
                        random method in the Math function.
                        Implements the switch/case method
*/
// change name in code, no interacivity at present.
// checks for no name given
var userName = "Bob";
if (userName === "") {
    console.log(`Hello!`)
} else {
    console.log(`Hello ${userName}!`)
}
// can change to ask any question
var userQuestion = "Will I win the lottery this week?";
console.log(`${userName} asks ${userQuestion}`);
randomNumber = (Math.floor(Math.random() * 8));
// can change value of eightball to provide any answer
switch (randomNumber) {
    case 0:
        eightBall = ("It is certain");
        break;
    case 1:
        eightBall = ("It is decidedly so");
        break;
    case 2:
        eightBall = ("Reply hazy try again");
        break;
    case 3:
        eightBall = ("Cannot predict now");
        break;
    case 4:
        eightBall = ("Do not count on it");
        break;
    case 5:
        eightBall = ("My sources say no");
        break;
    case 6:
        eightBall = ("Outlook not so good");
        break;
    case 7:
        eightBall = ("Signs point to yes");
        break;
}
console.log(randomNumber, eightBall);